pytrade2.tickers: "BTC-USDT"


#pytrade2.exchange: binance.BinanceExchange
#pytrade2.exchange.binance.spot.url: 'https://testnet.binance.vision'

pytrade2.exchange: "huobi.hbdm.HuobiExchangeHbdm"
#pytrade2.exchange.huobi.market.client.url: "https://api.huobi.pro"
#pytrade2.exchange.huobi.trade.client.url: "https://api.huobi.pro"
#pytrade2.exchange.huobi.account.client.url: "https://api.huobi.pro"

pytrade2.data.dir: '/data'

pytrade2.s3.enabled: true

# Predict next X min
pytrade2.strategy.learn.interval: "5min"
pytrade2.strategy.history.min.window: "5min"
pytrade2.strategy.history.max.window: "15min"
pytrade2.strategy.predict.window: "5min"
pytrade2.strategy.past.window: "5min"
pytrade2.strategy.riskmanager.wait_after_loss: 0min

pytrade2.feed.candles.periods: 5min, 15min
pytrade2.feed.candles.counts: 5, 5

pytrade2.strategy.profitloss.ratio: 3


# My buy/sell spot fee 0.12%*2=0.24% = 0.0024, for 30000 means 72
# My fut market fee 0.012% = 0.00012, 30K*0.00012*2=7.2 USDT
# 30K*0.0001=3 USDT
# 0.0003 ~=9USDT

# 30K*0.001=30 USDT
# For 30 USDT profit = 0.3 USDT
pytrade2.strategy.profit.min.coeff: 0.002
pytrade2.strategy.profit.max.coeff: 0.004

# 30K*0.001=30 USDT
# For 30 USDT loss 0.00 = 0.3 USDT
pytrade2.strategy.stoploss.min.coeff: 0.002
pytrade2.strategy.stoploss.max.coeff: 0.004

# 0.001 of 30000 = 30
pytrade2.order.quantity: 1
pytrade2.order.is_trailingstop: false

pytrade2.broker.comissionpct: 0.012
pytrade2.broker.trade.allow: false