version: 1
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout

formatters:
  simpleFormatter:
    format: "%(asctime)s %(levelname)s %(module)s - %(funcName)s: %(message)s"
    date_fmt: "%Y-%m-%d %H:%M:%s"

loggers:
  root:
    level: INFO
    handlers: [consoleHandler]
  HuobiBrokerHbdm:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: no
  LgbLowHighRegressionStrategy:
    level: INFO
    handlers: [consoleHandler]
    propagate: no
  CandlesFeed:
    level: INFO
    handlers: [consoleHandler]
    propagate: no
  MultiIndiFeatures:
    level: INFO
    handlers: [ consoleHandler ]
    propagate: no
