version: "3.9"
services:

#  grafana:
#    image: grafana/grafana-enterprise
#    container_name: grafana
#    restart: unless-stopped
#    ports:
#      - '3000:3000'

  trade:
    profiles: []
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - pytrade2
    volumes:
      - ./data:/data
      - ./pytrade2/cfg:/pytrade2/cfg
    command: python ./App.py --strategy None
    restart: always
    ports:
      - 8000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  lgblowhighregressionstrategy:
    container_name: lgblowhighregressionstrategy
    hostname: lgblowhighregressionstrategy
    env_file:
      - .lgblowhighregressionstrategy.env

    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy LgbLowHighRegressionStrategy
#
#  keraslowhighclassificationstrategy:
#    container_name: keraslowhighclassificationstrategy
#    extends:
#      service: trade
#    command: python ./App.py --pytrade2.strategy KerasLowHighClassificationStrategy
#
#  kerasbidaskregressionstrategy:
#    container_name: kerasbidaskregressionstrategy
#    extends:
#      service: trade
#    command: python ./App.py --pytrade2.strategy KerasBidAskRegressionStrategy

#  lstmbidaskregressionstrategy:
#    container_name: lstmbidaskregressionstrategy
#    extends:
#      service: trade
#    command: python ./App.py --pytrade2.strategy LSTMBidAskRegressionStrategy
#
#  lstmbidaskregressionstrategy2:
#    container_name: lstmbidaskregressionstrategy2
#    extends:
#      service: trade
#    command: python ./App.py --pytrade2.strategy LSTMBidAskRegressionStrategy2

networks:
  pytrade2:
    name: pytrade2
    external: true