{
 "title": "pytrade2 strategy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$[\"pytrade2.strategy\"]"
      },
      {
       "jsonPath": "$[\"pytrade2.broker.trade.allow\"]",
       "language": "jsonpath",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_signal >= 0",
     "legendFormat": "Buy"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_signal < 0",
     "legendFormat": "Sell"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_learn_train_period_sec"
    }
   ]
  },
  {
   "title": "Train duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_learn_train_exec_duration_sec"
    }
   ]
  },
  {
   "title": "In trade",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_broker_in_trade >= 0"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_broker_in_trade < 0"
    }
   ]
  },
  {
   "title": "Process duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_process_duration_sec"
    }
   ]
  },
  {
   "title": "Current profit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_broker_trade_profit >= 0",
     "legendFormat": "profit"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_broker_trade_profit < 0",
     "legendFormat": "loss"
    },
    {
     "expr": "((pytrade2_lgblowhighregressionstrategy_broker_trade_tp - pytrade2_lgblowhighregressionstrategy_broker_trade_open_price) * pytrade2_lgblowhighregressionstrategy_broker_in_trade) != 0",
     "legendFormat": "take profit"
    },
    {
     "expr": "((pytrade2_lgblowhighregressionstrategy_broker_trade_sl - pytrade2_lgblowhighregressionstrategy_broker_trade_open_price) * pytrade2_lgblowhighregressionstrategy_broker_in_trade) !=0",
     "legendFormat": "stop loss"
    }
   ]
  },
  {
   "title": "Predicted future low/high diff",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_pred_fut_low_diff",
     "legendFormat": "predicted fut low diff"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_pred_fut_high_diff",
     "legendFormat": "predicted fut high diff"
    }
   ]
  },
  {
   "title": "Account balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_broker_account_balance != 0"
    }
   ]
  },
  {
   "title": "Candles",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_feed_candles_open != 0"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_feed_candles_high != 0"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_feed_candles_low != 0"
    },
    {
     "expr": "pytrade2_lgblowhighregressionstrategy_strategy_feed_candles_close != 0"
    }
   ]
  },
  {
   "title": "App parameters",
   "type": "table",
   "description": "Application config, maybe overridden by app parameters",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 23 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "*~", "language": "jsonpath" },
      { "jsonPath": "*", "language": "jsonpath", "name": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "App initial config",
   "type": "table",
   "description": "Application config, maybe overridden by app parameters",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 29 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "*~" },
      { "jsonPath": "*", "language": "jsonpath", "name": "" }
     ],
     "method": "GET"
    }
   ]
  }
 ]
}