version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    #hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/prometheus/console_libraries'
      - '--web.console.templates=/prometheus/consoles'
    env_file:
      - ../../../.env

    networks:
      - pytrade2

  grafana:
    image: grafana/grafana:latest
    volumes:
#      - ~/prometheus-grafana/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - pytrade2-grafana:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    networks:
      - pytrade2

networks:
  pytrade2:
    name: pytrade2
    external: true
volumes:
  prometheus_data:
  pytrade2-grafana:
