apiVersion: v1
kind: Service
metadata:
  name: pytrade2
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000