replicaCount: 1

image:
  repository: ghcr.io/mlflow/mlflow
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 5000

env:
  file: ../../../.env
mlflow_auth_config:
  file: /home/dima/projects/pytrade2/deploy/docker/mlflow/mlflow_auth_config.ini

volumes:
  - name: mlruns
    hostPath:
      path: /path/to/mlruns
  - name: mlflow-auth-config
    hostPath:
      path: ../../../deploy/docker/mlflow/mlflow_auth_config.ini

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
