# Mlflow tracking
tracking:
  enabled: true
  auth:
    enabled: true
    existingSecret: pytrade2-mlflow-tracking
    existingSecretUserKey: admin-user
    existingSecretPasswordKey: admin-password

postgresql:
  enabled: true
  auth:
    database: bitnami_mlflow
    existingSecret: pytrade2-mlflow-postgresql

# No minio
minio:
  enabled: false

# Cloud s3
externalS3:
  host: "storage.yandexcloud.net"
  port: 443
  useCredentialsInSecret: true
  existingSecret: "pytrade2-mlflow-s3"
  existingSecretAccessKeyIDKey: "access-key-id"
  existingSecretKeySecretKey: "access-key-secret"
  protocol: "https"
  bucket: "pytrade2"
  serveArtifacts: true