tracking:
  enabled: true
  auth:
    enabled: true
    existingSecret: pytrade2-mlflow-tracking
    existingSecretUserKey: admin-user
    existingSecretPasswordKey: admin-password
    existingSecretFlaskServerSecretKey: flask-server-secret-key
  service:
    type: LoadBalancer
    nodePorts:
      http: "30180"
      https: "30180"

defaultBuckets: "pytrade2"

postgresql:
  enabled: true
  auth:
    database: bitnami_mlflow
    existingSecret: pytrade2-mlflow-postgresql

minio:
  enabled: false
  auth:
    existingSecret: pytrade2-mlflow-minio


# Local minikube minio
externalS3:
  host: "192.168.49.2"
  port: 30901
  useCredentialsInSecret: true
  existingSecret: "pytrade2-mlflow-minio"
  existingSecretAccessKeyIDKey: "root-user"
  existingSecretKeySecretKey: "root-password"
  protocol: "http"
  bucket: "pytrade2"
  serveArtifacts: true

# Cloud s3
#externalS3:
#  host: "storage.yandexcloud.net"
#  port: 443
#  useCredentialsInSecret: true
#  existingSecret: "pytrade2-mlflow-s3"
#  existingSecretAccessKeyIDKey: "access-key-id"
#  existingSecretKeySecretKey: "access-key-secret"
#  protocol: "https"
#  bucket: "pytrade2"
#  serveArtifacts: true

#ingress:
#  enabled: true
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#  hosts:
#    - host: "{{ .Values.global.pytrade2_external_ip }}"
#      paths:
#        - path: /mlflow(/|$)(.*)
#          pathType: ImplementationSpecific