apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytrade2-jenkins
  namespace: pytrade2
spec:
  storageClassName: ""
  volumeName: pytrade2-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
