spec:
  securityContext:
    fsGroup: 1000

persistence:
  enabled: true
  existingClaim: pytrade2-jenkins

controller:
  sidecars:
    docker:
      enabled: true
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersocket
          mountPath: /var/run/docker.sock
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
            type: Socket