
image:
  # Minikube default registry
  repository: "localhost:5000/pytrade2"
  tag: "latest"
  pullPolicy: IfNotPresent
  command: ["python", "./App.py"]

persistence:
  data:
    mountPath: "/pytrade2/data"
    existingClaim: "pytrade2-data"          # Use an existing PVC if needed

logConfig:
  "log.yaml": |
    version: 1
    handlers:
      consoleHandler:
        class: logging.StreamHandler
        level: NOTSET
        formatter: simpleFormatter
        stream: ext://sys.stdout
    
    formatters:
      simpleFormatter:
        format: "%(asctime)s %(levelname)s %(module)s - %(funcName)s: %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%s"
    
    loggers:
      root:
        level: INFO
        handlers: [ consoleHandler ]
      HuobiBrokerHbdm:
        level: INFO
        handlers: [ consoleHandler ]
        propagate: no
      LgbLowHighRegressionStrategy:
        level: INFO
        handlers: [ consoleHandler ]
        propagate: no
      MultiIndiFeatures:
        level: INFO
        handlers: [ consoleHandler ]
        propagate: no
      werkzeug:
        level: WARNING
        handlers: [ consoleHandler ]
        propagate: no

